linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - errorlint
    - exportloopref
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - gosec
    - interfacer
    - makezero
    - misspell
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unparam
    - whitespace
  disable:
    - gomnd
    - gci
    - wrapcheck
    - testpackage
    - paralleltest
    - nlreturn
    - ifshort
    - goerr113
    - exhaustivestruct
    - cyclop
    - wsl
    - unconvert
    - maligned
    - lll
    - godot
    - nakedret
    - gocyclo
    - funlen
    - goconst
    - gocognit
    - errcheck
    - dupl
    - exhaustive